project:
  type: book
  output-dir: docs

book:
  title: "AI Poker Tutorial"
  author: "Max Chiswick"
  date: "9/11/2024"
  cover-image: pcicon.png
  page-footer: "© 2024 poker.camp. All rights reserved."
  favicon: favicon.svg
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd

    - part: intro.qmd
      chapters: 
        - whypoker.qmd
        - pokercamp.qmd
        - problemsolving.qmd
        - games.qmd
        - basicstrategy.qmd
        - ethics.qmd

    - part: codingfoundations.qmd
      chapters: 
        - python.qmd
        - aiagents.qmd
        - buildingaiagents.qmd

    - part: mathfoundations.qmd
      chapters:
        - algebra.qmd
        - probability.qmd
        - combinatorics.qmd
        - expectedvalue.qmd
        - bayesrule.qmd
        - statistics.qmd
        - montecarlo.qmd

    - part: knowledge.qmd
      chapters:
        - logic.qmd
        - knowledgerepresentation.qmd
        - rationality.qmd
        - psychology.qmd

    - part: decisiomakingunderuncertainty.qmd
      chapters:
        - probabilisticthinking.qmd
        - decisiontheory.qmd
        - risk.qmd
        - regret.qmd
        - bandits.qmd

    - part: gametheory.qmd
      chapters:
        - nash.qmd
        - gto.qmd
        - mixedstrategies.qmd

    - part: gametrees.qmd
      chapters:
        - perfectinfo.qmd
        - minimax.qmd
        - imperfectinfo.qmd

    - part: solvingtoygames.qmd
      chapters:
        - analytical.qmd
        - normalform.qmd
        - optimization.qmd
        - sequenceform.qmd

    - part: cfr.qmd
      chapters:
        - algorithm.qmd
        - interactive.qmd
        - proof.qmd
        - algimprovements.qmd
        - montecarlocfr.qmd
        - vectorcfr.qmd

    - part: abstractinglargegames.qmd
      chapters:
        - gamesize.qmd
        - cardabstraction.qmd
        - betabstraction.qmd
        - agentevaluation.qmd

    - part: pokersolvers.qmd
      chapters:
        - howsolverswork.qmd
        - usingsolvers.qmd
        - generalizingsolvers.qmd
        - studyingpopulations.qmd
        - solverlimitations.qmd
        - advancedstrategy.qmd
        - tournaments.qmd

    - part: aimath.qmd
      chapters:
        - calculus.qmd
        - linearalgebra.qmd
        - infotheory.qmd

    - part: aifoundations.qmd
      chapters:
        - ml.qmd
        - dl.qmd
        - rl.qmd

    - part: recentgameaiadvances.qmd
      chapters:
        - gameai.qmd
        - mas.qmd

    - part: stateoftheartpokerai.qmd 
      chapters:
        - deepcfr.qmd
        - toppokeragents.qmd
        - variancereduction.qmd
        - humanvsai.qmd
        - newresearch.qmd

    - part: llms.qmd
      chapters:
        - transformers.qmd
        - othellogpt.qmd
        - pokergpt.qmd
        - interpretability.qmd

    - part: opponentmodeling.qmd
      chapters:
        - bestresponse.qmd
        - exploitativestrategies.qmd

    - part: aisafety.qmd
      chapters:
        - shortterm.qmd
        - longterm.qmd

    - part: theriver.qmd
      chapters:
        - trading.qmd
        - predictionmarkets.qmd
        - otherbetting.qmd

    - part: projectideas.qmd
      chapters:
        - projects.qmd

bibliography: references.bib

format:
  html:
    theme: cerulean
    math: true 
    toc: true
    toc-expand: true
    mathjax: 
      config: 
        text: 
          inlineMath: [['$', '$'], ['\\(', '\\)']]
  pdf:
    documentclass: scrreprt
