bibliography: references.bib
book:
  author: Max Chiswick
  chapters:
  - index.qmd
  - chapters:
    - intro/whypoker.qmd
    - intro/pokercamp.qmd
    - intro/problemsolving.qmd
    - intro/games.qmd
    - intro/basicstrategy.qmd
    - intro/ethics.qmd
    part: intro/intro.qmd
  - chapters:
    - codingfoundations/python.qmd
    - codingfoundations/aiagents.qmd
    - codingfoundations/buildingaiagents.qmd
    part: codingfoundations/codingfoundations.qmd
  - chapters:
    - mathfoundations/algebra.qmd
    - mathfoundations/probability.qmd
    - mathfoundations/combinatorics.qmd
    - mathfoundations/expectedvalue.qmd
    - mathfoundations/bayesrule.qmd
    - mathfoundations/statistics.qmd
    - mathfoundations/montecarlo.qmd
    part: mathfoundations/mathfoundations.qmd
  - chapters:
    - knowledge/logic.qmd
    - knowledge/knowledgerepresentation.qmd
    - knowledge/rationality.qmd
    - knowledge/psychology.qmd
    part: knowledge/knowledge.qmd
  - chapters:
    - decisiomakingunderuncertainty/probabilisticthinking.qmd
    - decisiomakingunderuncertainty/decisiontheory.qmd
    - decisiomakingunderuncertainty/risk.qmd
    - decisiomakingunderuncertainty/regret.qmd
    - decisiomakingunderuncertainty/bandits.qmd
    part: decisiomakingunderuncertainty/decisiomakingunderuncertainty.qmd
  - chapters:
    - gametheory/nash.qmd
    - gametheory/gto.qmd
    - gametheory/mixedstrategies.qmd
    part: gametheory/gametheory.qmd
  - chapters:
    - gametrees/perfectinfo.qmd
    - gametrees/minimax.qmd
    - gametrees/imperfectinfo.qmd
    part: gametrees/gametrees.qmd
  - chapters:
    - solvingtoygames/analytical.qmd
    - solvingtoygames/normalform.qmd
    - solvingtoygames/optimization.qmd
    - solvingtoygames/sequenceform.qmd
    part: solvingtoygames/solvingtoygames.qmd
  - chapters:
    - cfr/algorithm.qmd
    - cfr/interactive.qmd
    - cfr/cfrrpspoker.qmd
    - cfr/proof.qmd
    - cfr/algimprovements.qmd
    - cfr/montecarlocfr.qmd
    - cfr/vectorcfr.qmd
    part: cfr/cfr.qmd
  - chapters:
    - abstractinglargegames/gamesize.qmd
    - abstractinglargegames/cardabstraction.qmd
    - abstractinglargegames/betabstraction.qmd
    - abstractinglargegames/agentevaluation.qmd
    part: abstractinglargegames/abstractinglargegames.qmd
  - chapters:
    - pokersolvers/howsolverswork.qmd
    - pokersolvers/usingsolvers.qmd
    - pokersolvers/generalizingsolvers.qmd
    - pokersolvers/studyingpopulations.qmd
    - pokersolvers/solverlimitations.qmd
    - pokersolvers/advancedstrategy.qmd
    - pokersolvers/tournaments.qmd
    part: pokersolvers/pokersolvers.qmd
  - chapters:
    - aimath/calculus.qmd
    - aimath/linearalgebra.qmd
    - aimath/infotheory.qmd
    part: aimath/aimath.qmd
  - chapters:
    - aifoundations/ml.qmd
    - aifoundations/dl.qmd
    - aifoundations/rl.qmd
    part: aifoundations/aifoundations.qmd
  - chapters:
    - recentgameaiadvances/gameai.qmd
    - recentgameaiadvances/mas.qmd
    part: recentgameaiadvances/recentgameaiadvances.qmd
  - chapters:
    - stateoftheartpokerai/deepcfr.qmd
    - stateoftheartpokerai/toppokeragents.qmd
    - stateoftheartpokerai/variancereduction.qmd
    - stateoftheartpokerai/humanvsai.qmd
    - stateoftheartpokerai/newresearch.qmd
    part: stateoftheartpokerai/stateoftheartpokerai.qmd
  - chapters:
    - llms/transformers.qmd
    - llms/othellogpt.qmd
    - llms/pokergpt.qmd
    - llms/interpretability.qmd
    part: llms/llms.qmd
  - chapters:
    - opponentmodeling/bestresponse.qmd
    - opponentmodeling/exploitativestrategies.qmd
    part: opponentmodeling/opponentmodeling.qmd
  - chapters:
    - aisafety/shortterm.qmd
    - aisafety/longterm.qmd
    part: aisafety/aisafety.qmd
  - chapters:
    - theriver/trading.qmd
    - theriver/predictionmarkets.qmd
    - theriver/otherbetting.qmd
    part: theriver/theriver.qmd
  - chapters:
    - projectideas/projects.qmd
    part: projectideas/projectideas.qmd
  cover-image: pcicon.png
  date: 9/11/2024
  favicon: favicon.svg
  page-footer: "\xA9 2024 poker.camp. All rights reserved."
  sidebar:
    background: light
    style: docked
  title: 'Artificial Intelligence: Through the Lens of Poker'
format:
  html:
    math: true
    mathjax:
      config:
        text:
          inlineMath:
          - - $
            - $
          - - \\(
            - \\)
    theme: cerulean
    toc: true
    toc-expand: true
  pdf:
    documentclass: scrreprt
project:
  output-dir: docs
  type: book
