project:
  type: website
  output-dir: docs

website:
  title: "Expected Value Org"
  navbar: 
    background: primary
    right: 
      - text: "About"
        href: about.qmd
      - text: "Poker Camp"
        href: https://pokercamp.org
    tools: 
      - icon: twitter
        href: https://x.com/chisness
      - icon: github
        href: https://github.com/chisness/expectedvalue
  sidebar:
    style: docked
    background: light
    contents: 
      - section: "WHAT IS EXPECTED VALUE?"
        contents: 
          - href: ev-basics.qmd
            text: EV Basics
          - href: ev-benefits.qmd
            text: EV Benefits
          - href: ev-faults.qmd
            text: EV Faults
      - section: "EXPECTED VALUE EXAMPLES"
        contents: 
          - href: basketball.qmd
            text: Basketball
          - href: dice.qmd
            text: Dice
          - href: poker.qmd
            text: Poker
          - href: medicine.qmd
            text: Medicine
          - href: rice.qmd
            text: Rice
      - section: "CURRENT EVENTS"
        contents: 
          - href: gamestop.qmd
            text: Roaring Kitty Gamestop
          - href: huberman-pregnancy.qmd 
            text: Andrew Huberman Pregnancy Probability

format:
  html:
    theme: cerulean
    math: true 
    toc: true
    toc-expand: true
    mathjax: 
      config: 
        text: 
          inlineMath: [['$', '$'], ['\\(', '\\)']]