bibliography: references.bib
book:
  author: Max Chiswick
  chapters:
  - index.qmd
  - chapters:
    - intro/whypoker.qmd
    - intro/pokercamp.qmd
    - intro/problemsolving.qmd
    - intro/games.qmd
    - intro/basicstrategy.qmd
    - intro/ethics.qmd
    part: "Introduction"
  - chapters:
    - codingfoundations/python.qmd
    - codingfoundations/aiagents.qmd
    - codingfoundations/buildingaiagents.qmd
    part: "Coding Foundations"
  - chapters:
    - mathfoundations/algebra.qmd
    - mathfoundations/probability.qmd
    - mathfoundations/combinatorics.qmd
    - mathfoundations/expectedvalue.qmd
    - mathfoundations/bayesrule.qmd
    - mathfoundations/statistics.qmd
    - mathfoundations/montecarlo.qmd
    part: "Math Foundations"
  - chapters:
    - knowledge/logic.qmd
    - knowledge/knowledgerepresentation.qmd
    - knowledge/rationality.qmd
    - knowledge/psychology.qmd
    part: "Knowledge"
  - chapters:
    - decisiomakingunderuncertainty/probabilisticthinking.qmd
    - decisiomakingunderuncertainty/decisiontheory.qmd
    - decisiomakingunderuncertainty/risk.qmd
    - decisiomakingunderuncertainty/regret.qmd
    - decisiomakingunderuncertainty/bandits.qmd
    part: "Decision Making Under Uncertainty"
  - chapters:
    - gametheory/nash.qmd
    - gametheory/gto.qmd
    - gametheory/mixedstrategies.qmd
    part: "Game Theory"
  - chapters:
    - gametrees/perfectinfo.qmd
    - gametrees/minimax.qmd
    - gametrees/imperfectinfo.qmd
    part: "Game Trees"
  - chapters:
    - solvingtoygames/analytical.qmd
    - solvingtoygames/normalform.qmd
    - solvingtoygames/optimization.qmd
    - solvingtoygames/sequenceform.qmd
    part: "Solving Toy Games"
  - chapters:
    - cfr/algorithm.qmd
    - cfr/interactive.qmd
    - cfr/cfrrpspoker.qmd
    - cfr/proof.qmd
    - cfr/algimprovements.qmd
    - cfr/montecarlocfr.qmd
    - cfr/vectorcfr.qmd
    part: "Counterfactual Regret Minimization"
  - chapters:
    - abstractinglargegames/gamesize.qmd
    - abstractinglargegames/cardabstraction.qmd
    - abstractinglargegames/betabstraction.qmd
    - abstractinglargegames/agentevaluation.qmd
    part: "Abstracting Large Games"
  - chapters:
    - pokersolvers/howsolverswork.qmd
    - pokersolvers/usingsolvers.qmd
    - pokersolvers/generalizingsolvers.qmd
    - pokersolvers/studyingpopulations.qmd
    - pokersolvers/solverlimitations.qmd
    - pokersolvers/advancedstrategy.qmd
    - pokersolvers/tournaments.qmd
    part: "Poker Solvers"
  - chapters:
    - aimath/calculus.qmd
    - aimath/linearalgebra.qmd
    - aimath/infotheory.qmd
    part: "AI Math Foundations"
  - chapters:
    - aifoundations/ml.qmd
    - aifoundations/dl.qmd
    - aifoundations/rl.qmd
    part: "AI Foundations"
  - chapters:
    - recentgameaiadvances/gameai.qmd
    - recentgameaiadvances/mas.qmd
    part: "Recent Game AI Advances"
  - chapters:
    - stateoftheartpokerai/deepcfr.qmd
    - stateoftheartpokerai/toppokeragents.qmd
    - stateoftheartpokerai/variancereduction.qmd
    - stateoftheartpokerai/humanvsai.qmd
    - stateoftheartpokerai/newresearch.qmd
    part: "State of the Art Poker AI"
  - chapters:
    - llms/transformers.qmd
    - llms/othellogpt.qmd
    - llms/pokergpt.qmd
    - llms/interpretability.qmd
    part: "LLMs"
  - chapters:
    - opponentmodeling/bestresponse.qmd
    - opponentmodeling/exploitativestrategies.qmd
    part: "Opponent Modeling"
  - chapters:
    - aisafety/shortterm.qmd
    - aisafety/longterm.qmd
    part: "AI Risks and Safety"
  - chapters:
    - theriver/trading.qmd
    - theriver/predictionmarkets.qmd
    - theriver/otherbetting.qmd
    part: "The River"
  - chapters:
    - projectideas/projects.qmd
    part: "Project Ideas"
  cover-image: pcicon.png
  date: 9/11/2024
  favicon: favicon.svg
  page-footer: "\xA9 2024 poker.camp. All rights reserved."
  sidebar:
    background: light
    style: docked
    collapse-level: 1

  title: 'Artificial Intelligence: Through the Lens of Poker'
format:
  html:
    grid:
      sidebar-width: 360px
    math: true
    mathjax:
      config:
        text:
          inlineMath:
          - - $
            - $
          - - \\(
            - \\)
    theme: cerulean
    toc: true
    toc-expand: true
  pdf:
    documentclass: scrreprt
project:
  output-dir: docs
  type: book
