project:
  type: book
  output-dir: docs

book:
  title: "AI Poker Tutorial"
  author: "Max Chiswick"
  date: "9/11/2024"
  cover-image: pcicon.png
  page-footer: "© 2024 poker.camp. All rights reserved."
  favicon: favicon.svg
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd

    - part: "INTRO"
      chapters: 
        - whypoker.qmd
        - pokercamp.qmd
        - problemsolving.qmd
        - games.qmd
        - basicstrategy.qmd
        - ethics.qmd

    - part: "CODING FOUNDATIONS"
      chapters: 
        - python.qmd
        - aiagents.qmd
        - buildingaiagents.qmd

    - part: "MATH FOUNDATIONS"
      chapters:
        - algebra.qmd
        - probability.qmd
        - combinatorics.qmd
        - expectedvalue.qmd
        - bayesrule.qmd
        - statistics.qmd
        - montecarlo.qmd

    - part: "KNOWLEDGE"
      chapters:
        - logic.qmd
        - knowledgerepresentation.qmd
        - rationality.qmd
        - psychology.qmd

    - part: "DECISION MAKING UNDER UNCERTAINTY"
      chapters:
        - probabilisticthinking.qmd
        - decisiontheory.qmd
        - risk.qmd
        - regret.qmd
        - bandits.qmd

    - part: "GAME THEORY"
      chapters:
        - nash.qmd
        - gto.qmd
        - mixedstrategies.qmd

    - part: "GAME TREES"
      chapters:
        - perfectinfo.qmd
        - minimax.qmd
        - imperfectinfo.qmd

    - part: "SOLVING TOY GAMES"
      chapters:
        - analytical.qmd
        - normalform.qmd
        - optimization.qmd
        - sequenceform.qmd

    - part: "COUNTERFACTUAL REGRET MINIMIZATION (CFR)"
      chapters:
        - algorithm.qmd
        - interactive.qmd
        - proof.qmd
        - algimprovements.qmd
        - montecarlocfr.qmd
        - vectorcfr.qmd

    - part: "ABSTRACTING LARGE GAMES"
      chapters:
        - gamesize.qmd
        - cardabstraction.qmd
        - betabstraction.qmd
        - agentevaluation.qmd

    - part: "POKER SOLVERS"
      chapters:
        - howsolverswork.qmd
        - usingsolvers.qmd
        - generalizingsolvers.qmd
        - studyingpopulations.qmd
        - solverlimitations.qmd
        - advancedstrategy.qmd
        - tournaments.qmd

    - part: "AI MATH"
      chapters:
        - calculus.qmd
        - linearalgebra.qmd
        - infotheory.qmd

    - part: "AI FOUNDATIONS"
      chapters:
        - ml.qmd
        - dl.qmd
        - rl.qmd

    - part: "RECENT AI ADVANCES"
      chapters:
        - nonpoker.qmd
        - multiplayergames.qmd

    - part: "STATE OF THE ART POKER AI"
      chapters:
        - deepcfr.qmd
        - toppokeragents.qmd
        - variancereduction.qmd
        - humanvsai.qmd
        - newresearch.qmd

    - part: "LLMS"
      chapters:
        - transformers.qmd
        - othellogpt.qmd
        - pokergpt.qmd
        - interpretability.qmd

    - part: "OPPONENT MODELING"
      chapters:
        - bestresponse.qmd
        - exploitativestrategies.qmd

    - part: "AI RISKS AND SAFETY"
      chapters:
        - shortterm.qmd
        - longterm.qmd

    - part: "THE RIVER"
      chapters:
        - trading.qmd
        - predictionmarkets.qmd
        - otherbetting.qmd

    - part: "PROJECT IDEAS"
      chapters:
        - projects.qmd

bibliography: references.bib

format:
  html:
    theme: cerulean
    math: true 
    toc: true
    toc-expand: true
    mathjax: 
      config: 
        text: 
          inlineMath: [['$', '$'], ['\\(', '\\)']]
  pdf:
    documentclass: scrreprt
