project:
  type: book
  output-dir: docs

book:
  title: "AI Poker Tutorial"
  author: "Max Chiswick"
  date: "5/28/2024"
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - part: "Intro"
      chapters:
        - intro.qmd
        - trading.qmd
        - python.qmd
    - part: "Game Theory and Decision Making"
      chapters:
        - gametheory.qmd
        - decisionmaking.qmd
        - toypoker.qmd 
        - gametrees.qmd
    - part: "CFR and Solvers"
      chapters: 
        - cfr.qmd 
        - montecarlo.qmd
        - solvers.qmd 
    - part: "Machine Learning and Deep Learning"
      chapters: 
        - mlmath.qmd 
        - ml.qmd
        - dl.qmd
        - rl.qmd
    - part: "AI Poker Today"
      chapters: 
        - aiagents.qmd
        - recentai.qmd 
    - part: "Advanced Topics"
      chapters: 
        - opponentmodeling.qmd
        - llms.qmd
        - aisafety.qmd
    - part: "Projects"
      chapters: 
        - projects.qmd

bibliography: references.bib

format:
  html:
    theme: cerulean
    math: true 
  pdf:
    documentclass: scrreprt
