# GAME THEORY {#sec-gametheory}

Hello


A Nash equilibrium is a set of strategies, one for each player in the game. If the game is two-player and zero-sum, and if the players alternate positions to even out the advantage of playing in each position (as in poker games), then a Nash equilibrium has a useful theoretical property: it can do no worse than tie, on expectation, against any other opponent strategy. In a game such as poker, that "on expectation" is important: due to the luck in the game from the cards being randomly dealt, there is no guarantee that a Nash equilibrium (or any strategy!) will win every single hand. However, if you average over a large set of hands, or compute the expectation exactly, then it cannot to any worse than tie against anyone.

If the opponent also plays a Nash equilibrium strategy then they will tie; if the opponent carefully considers the Nash equilibrium strategy and computes a perfect counter-strategy then they will also tie. If the opponent makes mistakes, however, then they can lose value, allowing the Nash equilibrium strategy to win. In other words, a Nash equilibrium just plays perfect defence: it doesn't try to learn about or exploit the opponent's flaws, and instead just wins when the opponent makes mistakes. This is on purpose, since attempting to find and exploit an opponent's mistakes usually makes it possible for an even smarter opponent to exploit your new strategy. There's a tradeoff between playing defence and offence.

Since a Nash equilibrium is an unbeatable strategy for this type of game, it is considered to be an optimal strategy, and "solving" a game is equivalent to computing a Nash equilibrium. In this sense, "solve" is a technical term, meant in exactly the same sense that one might "solve for X" in a mathematical equation.